# Default build properties for ELTeC API
# To override use your private local.build.properties.

project.name=http://eltec.clscor.io/ns/exist
project.title=ELTeC API
project.abbrev=eltec
project.processorversion=6.4.0
build.dir=build
docker.port=8090
