name: eltec
services:
  api:
    image: "eltec/api"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_WEBHOOK_SECRET=qwerty
    environment:
      - EXIST_PASSWORD=
      - ELTEC_API_BASE=http://localhost:8090/exist/restxq/eltec/v1
    ports:
      - "8090:8080"
